version: "3.3"
services:
    spark-master:
      image: bde2020/spark-master:3.2.0-hadoop3.2
      container_name: spark-master
      ports:
        - "9090:8080"
        - "7077:7077"
      volumes:
        - ./apps:/opt/spark-apps
        - ./data:/opt/spark-data
      environment:
        - SPARK_LOCAL_IP=spark-master
        - SPARK_WORKLOAD=master
        - INIT_DAEMON_STEP=setup_spark
      depends_on:
        - kafka0
    spark-worker-1:
      image: bde2020/spark-worker:3.2.0-hadoop3.2
      ports:
        - "9091:8080"
        - "7000:7000"
      depends_on:
        - spark-master
      environment:
        - SPARK_MASTER=spark://spark-master:7077
        - SPARK_WORKER_CORES=1
        - SPARK_WORKER_MEMORY=1G
        - SPARK_DRIVER_MEMORY=1G
        - SPARK_EXECUTOR_MEMORY=1G
        - SPARK_WORKLOAD=worker
        - SPARK_LOCAL_IP=spark-worker-1
      volumes:
        - ./apps:/opt/spark-apps
        - ./data:/opt/spark-data

    kafka-ui:
        container_name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
          - 8080:8080
        depends_on:
          - zookeeper0
          - kafka0
        environment:
          KAFKA_CLUSTERS_0_NAME: local
          KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
          KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper0:2181
          KAFKA_CREATE_TOPICS: "mocked_data:1:1"

    zookeeper0:
      image: confluentinc/cp-zookeeper:5.2.4
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - 2181:2181

    kafka0:
      image: confluentinc/cp-kafka:5.3.1
      depends_on:
        - zookeeper0
      ports:
        - 9092:9092
        - 9997:9997
        - 29092:29092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        JMX_PORT: 9997
        KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9997
    
    data-generator:
      image: data_generator:1.0
      build: generator
      depends_on:
        - kafka-ui
        - kafka0
        - zookeeper0
